name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Match your Docker runtime now

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.0
        with:
          cli: latest

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build server uberjar
        run: |
          cd server
          clojure -T:build uber
          mkdir -p ../artifacts
          cp target/*standalone.jar ../artifacts/server-standalone-${{ env.VERSION }}.jar

      - name: Build proxy uberjar
        run: |
          cd proxy
          clojure -T:build uber
          mkdir -p ../artifacts
          cp target/*standalone.jar ../artifacts/proxy-standalone-${{ env.VERSION }}.jar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
