name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@12.0
        with:
          lein: '2.10.0'
          
      - name: Build server uberjar
        run: cd server && lein uberjar
        
      - name: Build proxy uberjar
        run: cd proxy && lein uberjar
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            server/target/*-standalone.jar
            proxy/target/*-standalone.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
